// src/components/greeting.jsx
import { h } from 'preact';
import { useState } from 'preact/hooks';

export default function Greeting({messages}) {

  const randomMessage = () => messages[(Math.floor(Math.random() * messages.length))];
  
  const [greeting, setGreeting] = useState(randomMessage());

  return (
    <div> 
      <h3>{greeting}! Så kjekt at du tar deg tid til å besøke siden <i>min</i>!🙏</h3>
      <button onClick={() => setGreeting(randomMessage())}>
        Ny hilsen
      </button>
    </div>
  );
}

// src/components/Greeting.vue
<template>
<h3>{{greeting}}! Så kjekt at du tar deg tid til å besøke siden <i>min</i>!🙏</h3>
</template>

<script lang="ts">
export default {
	setup() {
    const greetings = ["Hey", "Hei på deg", "Halla", "Hallo", "Hei", "Heia"]
    const greeting = greetings[Math.floor(Math.random()*greetings.length)];

		return {
      greeting,
		};
	},
};
</script>
